# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  test:
    cmds:
      - go test -run ""

  lint:
    cmds:
      - golangci-lint run